import { type FastifySchema } from "fastify";
import { PaymentMethod } from "../../lib/payment-method.js";

// POST /reserve
export const reserveTicketSchema: FastifySchema = {
    tags: ["Tickets"],
    description: "Reserve 1 or more seats for a specific event. This will create a temporary Redis lock, using a Lua script for guaranteed atomicity, on the seats for 15 minutes. The endpoint returns a signed JWT reservation token that can be used to complete the purchase with the [POST] /tickets/purchase endpoint. The endpoint also employes retry jitter to help avoid resource locks when multiple users are trying to reserve the same seats at the same time.",
    security: [{ bearerAuth: [] }],
    headers: {
        type: "object",
        required: ["authorization"],
        properties: {
            authorization: {
                type: "string",
                description: "Bearer JWT access token — 'Bearer <token>'",
                examples: ["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYmMxMjMifQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"]
            }
        }
    },
    body: {
        type: "object",
        required: ["seat_ids"],
        properties: {
            seat_ids: {
                type: "array",
                items: { type: "string" },
                description: "Array of UUIDs of seats to be reserved. These seats must all be from the same event.",
                examples: [["a1b2c3d4-e5f6-7890-abcd-ef1234567890", "b2c3d4e5-f6a7-8901-bcde-f12345678901"]]
            }
        }
    },
    response: {
        200: {
            description: "Proof of successful ticket reservation.",
            type: "object",
            properties: {
                reservation_token: { type: "string" },
                expires_at: { type: "number" },
                expires_at_string: { type: "string" }
            }
        },
        404: {
            description: "Seat or User did not exist.",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        },
        409: {
            description: "One of the seats has already been reserved.",
            type: "object",
            properties: {
                message: { type: "string" },
                conflict_seat_ids: {
                    type: "array", items: {
                        type: "string"
                    }
                }
            }
        },
        500: {
            description: "Internal server error",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        }
    }
}

// GET /demo/idempotency_key
export const getIdempotencyKeyForDemo: FastifySchema = {
    tags: ["Tickets"],
    description: "This endpoint is for demonstration purposes only. It generates an example idempotency key that can be used to test the idempotency of the [POST] /tickets/purchase endpoint. Generally the idempotency key would be automatically be generated by the frontend.",
    response: {
        200: {
            description: "Example Idempotency Key was generated successfully.",
            type: "object",
            properties: {
                idempotency_key: { type: "string" }
            }
        },
        500: {
            description: "Internal server error.",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        }
    }
}

// POST /reserve
export const createPaymentIntentSchema: FastifySchema = {
    tags: ["Tickets"],
    description: "This endpoint builds off of the reservation created by the [POST] /tickets/reserve endpoint. It takes the signed JWT reservation token to create a confirmed Stripe Payment Intent. This endpoint also uses the Redis locks set in the /tickets/reserve endpoint to check for potential seat conflicts and expired reservations before confirming the payment, and will return appropriate errors if any issues are found. Furthermore, the endpoint requires an idempotency key to be sent in the body of the request, which is used to prevent duplicate charges in the event that a request is retried due to a network failure or other issue.",
    security: [{ bearerAuth: [] }],
    headers: {
        type: "object",
        required: ["authorization"],
        properties: {
            authorization: {
                type: "string",
                description: "Bearer JWT access token — 'Bearer <token>'",
                examples: ["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhYmMxMjMifQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"]
            }
        }
    },
    body: {
        type: "object",
        required: ["reservation_token", "idempotency_key", "payment_method"],
        properties: {
            reservation_token: {
                type: "string",
                description: "JWT Signed Reservation token from [POST] /tickets/reserve endpoint",
                examples: ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWF0X2lkcyI6WyJhMWIyYzNkNCJdLCJ1c2VySWQiOiJ4eXoifQ.reservation_sig"]
            },
            idempotency_key: {
                type: "string",
                description: "Unique key that prevents duplicate charges if the request is retried. Use [GET] /tickets/demo/idempotency_key to generate one.",
                examples: ["f47ac10b-58cc-4372-a567-0e02b2c3d479"]
            },
            payment_method: {
                type: "string",
                enum: Object.keys(PaymentMethod),
                description: "Stripe test card identifier. Use SUCCESS_VISA for a happy-path purchase.",
                examples: ["SUCCESS_VISA"]
            }
        }
    },
    response: {
        200: {
            description: "Payment intent was successfully created.",
            type: "object",
            properties: {
                client_secret: { type: "string" },
                order_id: { type: "string" }
            }
        },
        402: {
            description: "Error from a failed payment method when confirming PaymentIntent",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        },
        403: {
            description: "One or more of the parameters are improperly configured.",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        },
        404: {
            description: "One or more of the parameters was invalid or did not exist.",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        },
        409: {
            description: "A resource, such as temporary seat lock, was expired.",
            type: "object",
            properties: {
                message: { type: "string" },
                conflict_seat_ids: {
                    type: "array", items: {
                        type: "string"
                    }
                }
            }
        },
        500: {
            description: "Internal server error.",
            type: "object",
            properties: {
                message: { type: "string" }
            }
        }
    }
}